// Package size checks non-test Go source against the C10 size limits.
package size

import (
	"go/ast"
	"strings"

	"golang.org/x/tools/go/analysis"

	"github.com/timlittle/omamessenger/tools/omalint/rules"
	"github.com/timlittle/omamessenger/tools/omalint/suppress"
)

var Analyzer = &analysis.Analyzer{
	Name: "size",
	Doc:  "check file, function and parameter counts against C10 limits",
	Run:  run,
}

func run(pass *analysis.Pass) (any, error) {
	suppress.Validate(pass)
	for _, file := range pass.Files {
		filename := pass.Fset.Position(file.Pos()).Filename
		if strings.HasSuffix(filename, "_test.go") || generated(file) {
			continue
		}
		checkFile(pass, file)
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Body == nil {
				continue
			}
			checkFunction(pass, fn)
		}
	}
	return nil, nil
}

func checkFile(pass *analysis.Pass, file *ast.File) {
	// Count physical lines, including leading and trailing comments; the AST
	// span from `package` to the last declaration under-counts.
	lines := pass.Fset.File(file.Pos()).LineCount()
	if lines > rules.MaxFileLines && !suppress.Check(pass, "size", file.Package) {
		pass.Reportf(file.Package, "size: file has %d lines; maximum is %d", lines, rules.MaxFileLines)
	}
}

func checkFunction(pass *analysis.Pass, fn *ast.FuncDecl) {
	start := pass.Fset.Position(fn.Pos()).Line
	end := pass.Fset.Position(fn.End()).Line
	lines := end - start + 1
	if lines > rules.MaxFunctionLines && !suppress.Check(pass, "size", fn.Pos()) {
		pass.Reportf(fn.Pos(), "size: function has %d lines; maximum is %d", lines, rules.MaxFunctionLines)
	}
	params := 0
	if fn.Type.Params != nil {
		for _, field := range fn.Type.Params.List {
			count := len(field.Names)
			if count == 0 {
				count = 1
			}
			params += count
		}
	}
	if params > rules.MaxParameters && !suppress.Check(pass, "size", fn.Pos()) {
		pass.Reportf(fn.Type.Params.Pos(), "size: function has %d parameters; maximum is %d", params, rules.MaxParameters)
	}
}

func generated(file *ast.File) bool {
	for _, group := range file.Comments {
		for _, comment := range group.List {
			if comment.Pos() > file.Package {
				break
			}
			if comment.Text == "// Code generated by" || strings.HasPrefix(comment.Text, "// Code generated ") {
				return true
			}
		}
	}
	return false
}
